# Generated by Django 4.2.4 on 2023-08-11 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(auto_now=True, verbose_name='Deleted at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Ship owner',
                'verbose_name_plural': 'Ship owners',
            },
        ),
        migrations.CreateModel(
            name='ShipType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(auto_now=True, verbose_name='Deleted at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Ship type',
                'verbose_name_plural': 'Ship types',
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(auto_now=True, verbose_name='Deleted at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('registry', models.CharField(max_length=255, verbose_name='Registry')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ships', verbose_name='Image')),
                ('pax', models.IntegerField(verbose_name='Pax')),
                ('length', models.IntegerField(verbose_name='Length')),
                ('fabrication_year', models.IntegerField(verbose_name='Fabrication year')),
                ('bathrooms', models.IntegerField(verbose_name='Bathrooms')),
                ('restrooms', models.IntegerField(verbose_name='Restrooms')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('reservations', models.TextField(verbose_name='Reservations')),
                ('reviews', models.TextField(verbose_name='Reviews')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships.shipowner', verbose_name='Ship owner')),
                ('ship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships.shiptype', verbose_name='Ship type')),
            ],
            options={
                'verbose_name': 'Ship',
                'verbose_name_plural': 'Ships',
            },
        ),
        migrations.CreateModel(
            name='HistoricalShipType',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, verbose_name='Deleted at')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Ship type',
                'verbose_name_plural': 'historical Ship types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShipOwner',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, verbose_name='Deleted at')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Ship owner',
                'verbose_name_plural': 'historical Ship owners',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShip',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, verbose_name='Deleted at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('registry', models.CharField(max_length=255, verbose_name='Registry')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Image')),
                ('pax', models.IntegerField(verbose_name='Pax')),
                ('length', models.IntegerField(verbose_name='Length')),
                ('fabrication_year', models.IntegerField(verbose_name='Fabrication year')),
                ('bathrooms', models.IntegerField(verbose_name='Bathrooms')),
                ('restrooms', models.IntegerField(verbose_name='Restrooms')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('reservations', models.TextField(verbose_name='Reservations')),
                ('reviews', models.TextField(verbose_name='Reviews')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ships.shipowner', verbose_name='Ship owner')),
                ('ship_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ships.shiptype', verbose_name='Ship type')),
            ],
            options={
                'verbose_name': 'historical Ship',
                'verbose_name_plural': 'historical Ships',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
