# Generated by Django 4.2.4 on 2023-08-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_historicaluser_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='reviews',
            field=models.TextField(blank=True, null=True, verbose_name='Reviews'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='ships',
            field=models.TextField(blank=True, null=True, verbose_name='Ships'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='reviews',
            field=models.TextField(blank=True, null=True, verbose_name='Reviews'),
        ),
        migrations.AddField(
            model_name='user',
            name='ships',
            field=models.TextField(blank=True, null=True, verbose_name='Ships'),
        ),
    ]
